# Generated by Django 5.0.7 on 2025-05-30 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
